version: "3.7"
services:
  eks-quickstart:
    build:
      context: ./
    ports:
      - 5000:5000
    environment:
      - BUCKET=${BUCKET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
