apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      - system:node-proxier
      rolearn: arn:aws:iam::316516050658:role/eks_fargate_general
      username: system:node:{{SessionName}}
    - groups:
      - leader-group
      rolearn: arn:aws:iam::316516050658:role/eks-leader-role
      username: eks-leader-role:{{SessionName}}
    - groups:
      - developers-group
      rolearn: arn:aws:iam::316516050658:role/eks-developers-role
      username: eks-developers-role:{{SessionName}}
  mapUsers: |
    - userarn: arn:aws:iam::316516050658:user/github-action
      username: github-action
      groups:
        - leader-group
